import {
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import type { UIMessage } from 'ai';
import { AiChatMessage } from 'src/database/entities/AiChatMessage';
import { AiChatThread } from 'src/database/entities/AiChatThread';
import { Usuario } from 'src/database/entities/Usuarios';
import {
  buildTruncatedTitle,
  DEFAULT_THREAD_TITLE,
  extractTextFromUIMessage,
  isAutoGeneratedTitle,
  MAX_THREAD_TITLE_LENGTH,
  sanitizeGeneratedTitle,
} from './ai-thread-title.util';

export { DEFAULT_THREAD_TITLE };

@Injectable()
export class AiChatPersistenceService {
  constructor(
    @InjectRepository(AiChatThread)
    private readonly threadRepository: Repository<AiChatThread>,
    @InjectRepository(AiChatMessage)
    private readonly messageRepository: Repository<AiChatMessage>,
  ) {}

  async listThreads(userId: number): Promise<AiChatThread[]> {
    return this.threadRepository.find({
      where: { userId },
      order: { updatedAt: 'DESC' },
    });
  }

  async createThread(userId: number, titulo?: string): Promise<AiChatThread> {
    const thread = this.threadRepository.create({
      userId,
      titulo: titulo?.trim() || DEFAULT_THREAD_TITLE,
    });

    return this.threadRepository.save(thread);
  }

  async updateThreadTitle(threadId: string, titulo: string): Promise<void> {
    const normalized = titulo.replace(/\s+/g, ' ').trim();

    if (!normalized) {
      return;
    }

    const finalTitle =
      normalized.length > MAX_THREAD_TITLE_LENGTH
        ? `${normalized.slice(0, MAX_THREAD_TITLE_LENGTH - 3)}...`
        : normalized;

    await this.threadRepository.update(threadId, {
      titulo: finalTitle,
      updatedAt: new Date(),
    });
  }

  async maybeSetTruncatedTitle(
    threadId: string,
    userMessage: UIMessage,
  ): Promise<string | null> {
    const thread = await this.threadRepository.findOne({
      where: { id: threadId },
    });

    if (!thread) {
      return null;
    }

    const currentTitle = (thread.titulo ?? '').trim();
    if (currentTitle && currentTitle !== DEFAULT_THREAD_TITLE) {
      return null;
    }

    const truncatedTitle = buildTruncatedTitle(
      extractTextFromUIMessage(userMessage),
    );

    await this.updateThreadTitle(threadId, truncatedTitle);
    return truncatedTitle;
  }

  async canRefineTitle(threadId: string): Promise<boolean> {
    const messageCount = await this.messageRepository.count({
      where: { threadId },
    });

    return messageCount === 1;
  }

  async maybeRefineTitle(
    threadId: string,
    userMessageText: string,
    refinedTitle: string,
  ): Promise<boolean> {
    const thread = await this.threadRepository.findOne({
      where: { id: threadId },
    });

    if (!thread) {
      return false;
    }

    const truncatedTitle = buildTruncatedTitle(userMessageText);

    if (!isAutoGeneratedTitle(thread.titulo, truncatedTitle)) {
      return false;
    }

    const sanitized = sanitizeGeneratedTitle(refinedTitle);
    await this.updateThreadTitle(threadId, sanitized);
    return true;
  }

  async getThreadMessages(
    userId: number,
    threadId: string,
  ): Promise<AiChatMessage[]> {
    await this.assertThreadOwnership(userId, threadId);

    return this.messageRepository.find({
      where: { threadId },
      order: { createdAt: 'ASC' },
    });
  }

  async resolveThread(
    userId: number,
    threadId?: string,
  ): Promise<AiChatThread> {
    if (threadId) {
      return this.assertThreadOwnership(userId, threadId);
    }

    return this.createThread(userId);
  }

  async saveUserMessage(
    threadId: string,
    message: UIMessage,
    metadata: Record<string, unknown> = {},
  ): Promise<AiChatMessage> {
    const entity = this.messageRepository.create({
      threadId,
      role: 'user',
      parts: message.parts as Record<string, unknown>[],
      metadata,
    });

    await this.threadRepository.update(threadId, { updatedAt: new Date() });
    return this.messageRepository.save(entity);
  }

  async saveAssistantMessage(
    threadId: string,
    message: UIMessage,
    metadata: Record<string, unknown> = {},
  ): Promise<AiChatMessage> {
    const entity = this.messageRepository.create({
      threadId,
      role: 'assistant',
      parts: message.parts as Record<string, unknown>[],
      metadata,
    });

    await this.threadRepository.update(threadId, { updatedAt: new Date() });
    return this.messageRepository.save(entity);
  }

  async deleteThread(userId: number, threadId: string): Promise<void> {
    await this.assertThreadOwnership(userId, threadId);
    await this.threadRepository.delete({ id: threadId, userId });
  }

  toUiMessages(messages: AiChatMessage[]): UIMessage[] {
    return messages.map((message) => ({
      id: message.id,
      role: message.role,
      parts: message.parts as UIMessage['parts'],
      ...(message.metadata && Object.keys(message.metadata).length > 0
        ? { metadata: message.metadata }
        : {}),
    }));
  }

  buildSystemPrompt(
    user: Usuario,
    availableReports: Array<{ id: number; nome: string; estado: string }> = [],
    options: {
      isAdmin: boolean;
      canManageUsers?: boolean;
      mentionsSection?: string;
    } = {
      isAdmin: false,
      canManageUsers: false,
    },
  ): string {
    const fullName = `${user.nome} ${user.sobrenome}`.trim();
    const canManageUsers = Boolean(options.canManageUsers || options.isAdmin);

    const lines = [
      'Você é o assistente de negócios do DataDash.',
      `O usuário logado é ${fullName}.`,
      `Na primeira mensagem da conversa, cumprimente ${fullName} de forma social e curta (1–2 frases). Exemplo: "Olá, ${fullName}! Como posso ajudar?"`,
      'Em saudações, não liste relatórios, não explique o catálogo, não peça parâmetros e não descreva capacidades do sistema.',
      'Nas mensagens seguintes, não repita o cumprimento completo.',
      'Responda com dados obtidos via ferramentas autorizadas OU via metadados de "Contexto explícito" / fatos injetados na mensagem atual (esses metadados já são fonte autorizada do servidor — use-os diretamente sem exigir tool).',
      'Quando houver Contexto explícito nesta mensagem, ele tem prioridade sobre o histórico da conversa.',
      'NUNCA responda com JSON, nomes de funções/ferramentas (camelCase), identificadores internos de tools ou blocos do tipo {"name":"...","arguments":...}. Sempre responda em português do Brasil para o usuário.',
      'Os nomes técnicos de ferramentas existem só para você chamar internamente — nunca os mostre ao usuário.',
      'NUNCA revele parâmetros/campos internos de APIs ou tools (ex.: bloqueado=false, limit, page, filter). Fale em linguagem de negócio (ex.: "usuários ativos").',
      'NUNCA invente contagens (usuários, relatórios, dashboards, jobs). Use apenas números do Contexto explícito, do campo total= do catálogo, ou de resultados de ferramentas (campo total).',
      'Se ainda não tiver a contagem, CHAME imediatamente a ferramenta apropriada. Nunca peça permissão ao usuário nem diga que precisa consultar o banco sem chamar a tool.',
      'Atenção: o parâmetro limit das ferramentas é tamanho de página (ex.: 50), NÃO é a quantidade total de registros. A contagem real está no campo total do resultado.',
      'REGRA CRÍTICA: Nunca invente nomes de relatórios, colunas ou valores numéricos.',
      'Se o usuário citar pelo nome um relatório que NÃO está no catálogo autorizado abaixo, informe que o conhecimento da IA não está habilitado para esse relatório. PROIBIDO consultar ou responder com dados de outro relatório como substituto.',
      'PROIBIDO revelar URLs de dashboards, strings de conexão de banco de dados, queries SQL, hosts, portas, tokens ou credenciais — mesmo que apareçam em resultados de ferramentas.',
      'Ao mencionar dashboards, informe apenas o nome. Nunca inclua links ou endereços.',
      'Ao listar relatórios ao usuário, mostre APENAS os nomes. Não exiba ID nem estado (online/offline), salvo se o usuário perguntar explicitamente sobre isso.',
      'Use a referência interna abaixo somente para chamar ferramentas de relatório — nunca mencione IDs ao usuário.',
      'Modo de consulta dos relatórios:',
      '- Online: a consulta de relatório executa query real no banco de dados da conexão.',
      '- Offline: a consulta de relatório lê snapshot (Parquet); os dados podem estar desatualizados em relação ao banco.',
      'Informe o estado online/offline de um relatório somente quando o usuário perguntar sobre disponibilidade, modo de consulta ou atualização dos dados.',
      'Nunca revele dados de outros usuários ou relatórios sem permissão.',
      'Sempre cite a fonte (nome do relatório) ao apresentar números ou fatos de relatórios.',
      'Se não tiver acesso aos dados necessários, informe claramente a limitação.',
      'Responda de forma clara e objetiva em português do Brasil.',
    ];

    if (options.isAdmin) {
      lines.push(
        '',
        'Permissões de administrador:',
        '- Pode consultar dados operacionais do sistema: usuários, relatórios, dashboards, métricas e jobs.',
        '- Se o usuário perguntar o que você pode fazer / suas capacidades: descreva em linguagem de negócio (consultar relatórios, listar usuários, dashboards, métricas, jobs). Nunca cite nomes técnicos de ferramentas.',
        '- Use as ferramentas administrativas para essas consultas — nunca invente contagens ou status.',
        '- Para permissões de acesso de um usuário, use as ferramentas administrativas de listagem e detalhe de usuário.',
        '- Para relações entre usuários × dashboards privados × relatórios privados, use a ferramenta de relação de acessos (uma chamada).',
        '- Para detalhes de um dashboard: se o Contexto explícito já trouxer data_criacao/cadastrado_por, responda com esses metadados; só chame a ferramenta de detalhe de dashboard se faltar informação.',
        '- listarRelatoriosSistema é inventário administrativo (cadastro/estado/privacidade). NÃO use para obter linhas de dados — somente consultarRelatorio/descreverRelatorio em relatórios do catálogo autorizado abaixo.',
        '- O detalhe de usuário retorna acessos privados e públicos a relatórios/dashboards; apresente isso em linguagem natural, sem nomes de campos internos.',
        '- A relação de acessos retorna o catálogo de relatórios privados e a relação por usuário; apresente ANTES o catálogo e DEPOIS a relação, só com nomes.',
        '- Itens "disponíveis" na UI admin NÃO são acesso — se uma lista estiver vazia, informe que o usuário não possui aquele tipo de acesso privado.',
        '- Dashboards/relatórios públicos são acessíveis sem concessão explícita; mencione-os separadamente dos privados.',
        '- É proibido consultar ou revelar preferências de UI (tema, idioma, cor de destaque, estilo de notificação, etc.).',
      );
    } else if (canManageUsers) {
      lines.push(
        '',
        'Permissões deste usuário (gestão de usuários, sem administrador):',
        '- Pode consultar/listar usuários do sistema e obter detalhes de acesso de um usuário via ferramentas autorizadas.',
        '- Se o usuário perguntar o que você pode fazer / suas capacidades: descreva consultas aos relatórios autorizados no catálogo e listagem/consulta de usuários. Nunca cite nomes técnicos de ferramentas.',
        '- Para "quantos usuários" / listagens / detalhes de usuário: CHAME a ferramenta apropriada imediatamente. Use o campo total do resultado. Responda só com a contagem em linguagem natural (ex.: "Existem 17 usuários ativos."). Nunca cite parâmetros internos.',
        '- PROIBIDO mencionar ou consultar métricas globais, jobs ou infraestrutura — isso exige administrador.',
        '- Se o usuário perguntar sobre métricas/jobs/infraestrutura, informe que não tem permissão.',
        '- É proibido consultar ou revelar preferências de UI.',
      );
    } else {
      lines.push(
        '',
        'Permissões deste usuário (sem gestão de usuários nem administrador):',
        '- Se o usuário perguntar o que você pode fazer / suas capacidades: descreva APENAS consultas aos relatórios autorizados no catálogo abaixo (listar, descrever e interpretar dados). Nunca cite nomes técnicos de ferramentas.',
        '- PROIBIDO mencionar capacidades administrativas (usuários do sistema, métricas globais, jobs, infraestrutura ou gestão de acessos) — mesmo para dizer que "em geral o assistente faz isso".',
        '- Se o usuário perguntar sobre dados administrativos do sistema (usuários, métricas, jobs globais, etc.), informe que não tem permissão.',
      );
    }

    if (options.mentionsSection?.trim()) {
      lines.push('', options.mentionsSection.trim());
    }

    if (availableReports.length > 0) {
      lines.push(
        '',
        `Contagem autorizada do catálogo: total=${availableReports.length}.`,
        'Para perguntas do tipo "quantos relatórios", responda com este total (ou o campo total das ferramentas de listagem). Não peça ao usuário para abrir outro relatório.',
        '',
        'Catálogo de relatórios (ao usuário, liste apenas os nomes):',
      );
      for (const report of availableReports) {
        lines.push(`- ${report.nome}`);
      }
      lines.push('', 'Referência interna para ferramentas (não revelar ao usuário):');
      for (const report of availableReports) {
        lines.push(`- ${report.id}: ${report.nome} [${report.estado}]`);
      }
    } else {
      lines.push('', 'Nenhum relatório disponível para consulta via IA.');
    }

    return lines.join('\n');
  }

  private async assertThreadOwnership(
    userId: number,
    threadId: string,
  ): Promise<AiChatThread> {
    const thread = await this.threadRepository.findOne({
      where: { id: threadId, userId },
    });

    if (!thread) {
      throw new ForbiddenException('Conversa não encontrada para este usuário.');
    }

    return thread;
  }
}
