import type { UIMessage } from 'ai';

export const DEFAULT_THREAD_TITLE = 'Nova conversa';
export const MAX_THREAD_TITLE_LENGTH = 80;
const TRUNCATE_LENGTH = 60;

export function extractTextFromUIMessage(message: UIMessage): string {
  return message.parts
    .filter((part): part is { type: 'text'; text: string } => part.type === 'text')
    .map((part) => part.text)
    .join('')
    .trim();
}

export function buildTruncatedTitle(text: string): string {
  const normalized = text.replace(/\s+/g, ' ').trim();

  if (!normalized) {
    return DEFAULT_THREAD_TITLE;
  }

  if (normalized.length <= TRUNCATE_LENGTH) {
    return normalized;
  }

  return `${normalized.slice(0, TRUNCATE_LENGTH - 3)}...`;
}

export function sanitizeGeneratedTitle(text: string): string {
  const cleaned = text
    .replace(/^["'`]+|["'`]+$/g, '')
    .replace(/[\r\n]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[.!?]+$/g, '');

  if (!cleaned) {
    return DEFAULT_THREAD_TITLE;
  }

  if (cleaned.length <= MAX_THREAD_TITLE_LENGTH) {
    return cleaned;
  }

  return `${cleaned.slice(0, MAX_THREAD_TITLE_LENGTH - 3)}...`;
}

/** Detecta raciocínio/meta-comentário em inglês comum em modelos tipo Nemotron. */
export function looksLikeReasoningPreamble(text: string): boolean {
  const normalized = text.replace(/\s+/g, ' ').trim();
  if (!normalized) {
    return false;
  }

  if (
    /^(okay|ok[,.]?\s|the user|we need to|let me|i need to|i'll|i will|based on|looking at|alright)/i.test(
      normalized,
    )
  ) {
    return true;
  }

  return (
    normalized.length > 50 &&
    /\b(generate a (short )?title|chat conversation|based on their message|translates to)\b/i.test(
      normalized,
    )
  );
}

/**
 * Extrai um título curto do output do modelo.
 * Modelos com reasoning podem prefixar o título com raciocínio em inglês.
 */
export function extractTitleCandidate(
  rawText: string,
  fallback: string,
): string {
  const lines = rawText
    .split(/[\r\n]+/)
    .map((line) => line.trim())
    .filter(Boolean);

  const candidates =
    lines.length > 0 ? [...lines].reverse() : [rawText.trim()];

  for (const candidate of candidates) {
    const sanitized = sanitizeGeneratedTitle(candidate);
    if (sanitized === DEFAULT_THREAD_TITLE) {
      continue;
    }
    if (looksLikeReasoningPreamble(sanitized)) {
      continue;
    }
    const wordCount = sanitized.split(/\s+/).filter(Boolean).length;
    if (wordCount > 0 && wordCount <= 8) {
      return sanitized;
    }
  }

  const whole = sanitizeGeneratedTitle(rawText);
  if (
    whole !== DEFAULT_THREAD_TITLE &&
    !looksLikeReasoningPreamble(whole) &&
    whole.split(/\s+/).filter(Boolean).length <= 8
  ) {
    return whole;
  }

  return fallback || DEFAULT_THREAD_TITLE;
}

export function isAutoGeneratedTitle(
  current: string | null | undefined,
  truncated: string,
): boolean {
  const normalizedCurrent = (current ?? '').trim();

  if (!normalizedCurrent || normalizedCurrent === DEFAULT_THREAD_TITLE) {
    return true;
  }

  return normalizedCurrent === truncated;
}
