import {
  buildTruncatedTitle,
  DEFAULT_THREAD_TITLE,
  extractTextFromUIMessage,
  extractTitleCandidate,
  isAutoGeneratedTitle,
  looksLikeReasoningPreamble,
  sanitizeGeneratedTitle,
} from './ai-thread-title.util';

describe('ai-thread-title.util', () => {
  it('extracts text from ui message parts', () => {
    const text = extractTextFromUIMessage({
      id: '1',
      role: 'user',
      parts: [
        { type: 'text', text: 'Quantos ' },
        { type: 'text', text: 'usuários?' },
      ],
    });

    expect(text).toBe('Quantos usuários?');
  });

  it('truncates long titles', () => {
    const longText = 'a'.repeat(80);
    const title = buildTruncatedTitle(longText);

    expect(title.endsWith('...')).toBe(true);
    expect(title.length).toBeLessThanOrEqual(60);
  });

  it('returns default title for empty text', () => {
    expect(buildTruncatedTitle('   ')).toBe(DEFAULT_THREAD_TITLE);
  });

  it('sanitizes generated title', () => {
    expect(sanitizeGeneratedTitle('"Relatório de vendas."')).toBe('Relatório de vendas');
  });

  it('detects english reasoning preambles from nemotron-like models', () => {
    expect(
      looksLikeReasoningPreamble(
        'Okay, the user wants me to generate a short title for a chat conversation',
      ),
    ).toBe(true);
    expect(looksLikeReasoningPreamble('Quantidade de usuários')).toBe(false);
  });

  it('extracts portuguese title and ignores english reasoning', () => {
    expect(
      extractTitleCandidate(
        'Okay, the user wants a short title.\nQuantidade de usuários',
        'fallback',
      ),
    ).toBe('Quantidade de usuários');

    expect(
      extractTitleCandidate(
        'Okay, the user wants me to generate a short title for a chat conversation based on their message',
        'quantos usuários existem?',
      ),
    ).toBe('quantos usuários existem?');
  });

  it('detects auto generated titles', () => {
    const truncated = buildTruncatedTitle('Quantos usuários possui?');

    expect(isAutoGeneratedTitle(DEFAULT_THREAD_TITLE, truncated)).toBe(true);
    expect(isAutoGeneratedTitle(truncated, truncated)).toBe(true);
    expect(isAutoGeneratedTitle('Título customizado', truncated)).toBe(false);
  });
});
