import type { UIMessage } from 'ai';

export const DEFAULT_THREAD_TITLE = 'Nova conversa';
export const MAX_THREAD_TITLE_LENGTH = 80;
const TRUNCATE_LENGTH = 60;

export function extractTextFromUIMessage(message: UIMessage): string {
  return message.parts
    .filter((part): part is { type: 'text'; text: string } => part.type === 'text')
    .map((part) => part.text)
    .join('')
    .trim();
}

export function buildTruncatedTitle(text: string): string {
  const normalized = text.replace(/\s+/g, ' ').trim();

  if (!normalized) {
    return DEFAULT_THREAD_TITLE;
  }

  if (normalized.length <= TRUNCATE_LENGTH) {
    return normalized;
  }

  return `${normalized.slice(0, TRUNCATE_LENGTH - 3)}...`;
}

export function sanitizeGeneratedTitle(text: string): string {
  const cleaned = text
    .replace(/^["'`]+|["'`]+$/g, '')
    .replace(/[\r\n]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[.!?]+$/g, '');

  if (!cleaned) {
    return DEFAULT_THREAD_TITLE;
  }

  if (cleaned.length <= MAX_THREAD_TITLE_LENGTH) {
    return cleaned;
  }

  return `${cleaned.slice(0, MAX_THREAD_TITLE_LENGTH - 3)}...`;
}

export function isAutoGeneratedTitle(
  current: string | null | undefined,
  truncated: string,
): boolean {
  const normalizedCurrent = (current ?? '').trim();

  if (!normalizedCurrent || normalizedCurrent === DEFAULT_THREAD_TITLE) {
    return true;
  }

  return normalizedCurrent === truncated;
}
